spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/trace?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  mvc:
    problem-details:
      enabled: true
    log-request-details: true
  codec:
    log-request-details: true
  application:
    name: trace-system
  cache:
    type: redis

trace:
  snowflake:
    node-id:
      timeout-hour: 1
      redis-expire-job: 0 0/50 * * * ?

logging:
  level:
    web: debug
    com.refout: debug

server:
  shutdown: graceful
  port: 8081