### 登录
POST http://localhost:8080/login
Accept: application/json
Content-Type: application/json

{
  "principal": "admin",
  "credentials": "123456",
  "captchaCode": "tfIe",
  "captchaId": "6f03cadb061946f090460b09c17e2e5a"
}

> {%
    client.log(response.body.data.token);
    client.global.set("auth_token", response.body.data.token);
%}

###登出
DELETE http://localhost:8080/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### 获取验证码
GET http://localhost:8080/captcha

### 注册
POST http://localhost:8080/register
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "zhangsan",
  "password": "123456",
  "nickname": "张三",
  "email": "",
  "phone": "13000000000",
  "gender": "1",
  "avatar": ""
}

###用户分页查询
POST http://localhost:8081/system/user/page
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "page": 1,
  "size": 3,
  "query": {
    "data": {
      "username": "zhan",
      "phone": "13",
      "delete": false
    },
    "scopes": [
      {
        "columnName": "createTime",
        "start": "2023-07-07 00:00:00.000",
        "end": "2023-08-15 00:00:00.000"
      }
    ],
    "ins": [
      {
        "columnName": "id",
        "in": [
          1685959186967429120,
          1685959221486551040,
          1685959240750989312,
          1685959248783081472,
          1686695021438308352
        ]
      }
    ]
  },
  "orderBy": [
    {
      "direction": 0,
      "property": "email"
    },
    {
      "direction": 1,
      "property": "phone"
    },
    {
      "direction": "DESC",
      "property": "username"
    }
  ]
}

###
###
GET http://localhost:8081/system/user/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}